name: icollector 
channels: !!python/tuple
- defaults
dependencies:
- python=3.5.2=0
- flask=0.11.1=py35_0
- click=6.6=py35_0
- pyyaml=3.12=py35_0
- requests=2.12.3=py35_0
- pip:
  - enum34==1.1.6
  - grpcio==1.0.4
  - grpcio-tools==1.0.4
  - protobuf==3.1.0.post1

